import type { YearlyData } from "./types"

export const paymentVolumeData: YearlyData = {
  "2024": [
    { month: "Jan", volume: 40 },
    { month: "Feb", volume: 20 },
    { month: "Mar", volume: 45 },
    { month: "Apr", volume: 30 },
    { month: "May", volume: 5 },
    { month: "June", volume: 15 },
    { month: "July", volume: 70 },
    { month: "Aug", volume: 40 },
    { month: "Sep", volume: 35 },
    { month: "Oct", volume: 85 },
    { month: "Nov", volume: 25 },
    { month: "Dec", volume: 95 },
  ],
  "2023": [
    { month: "Jan", volume: 30 },
    { month: "Feb", volume: 35 },
    { month: "Mar", volume: 40 },
    { month: "Apr", volume: 45 },
    { month: "May", volume: 50 },
    { month: "June", volume: 55 },
    { month: "July", volume: 60 },
    { month: "Aug", volume: 65 },
    { month: "Sep", volume: 70 },
    { month: "Oct", volume: 75 },
    { month: "Nov", volume: 80 },
    { month: "Dec", volume: 85 },
  ],
  "2022": [
    { month: "Jan", volume: 15 },
    { month: "Feb", volume: 25 },
    { month: "Mar", volume: 35 },
    { month: "Apr", volume: 45 },
    { month: "May", volume: 55 },
    { month: "June", volume: 45 },
    { month: "July", volume: 35 },
    { month: "Aug", volume: 25 },
    { month: "Sep", volume: 15 },
    { month: "Oct", volume: 25 },
    { month: "Nov", volume: 35 },
    { month: "Dec", volume: 45 },
  ],
}

