import { auth } from "@/auth";
import AppProvider from "@/provider/AppProvider";
import NProgress from "@/provider/NProgress";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Pacific Rim Fusion",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <AppProvider>
        <html lang="en">
          <body className={` ${inter.className} antialiased`}>
            <main>
              <div>{children}</div>
              <div>
                <NProgress />
              </div>
            </main>
          </body>
        </html>
      </AppProvider>
    </SessionProvider>
  );
}
